# Site settings
baseurl: ""
url: "http://inventables.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
- jekyll-textile-converter
- github-pages
- octopress-autoprefixer
- jekyll-assets
